### ISSUE TITLE
Proxy all - no direct at all

### ISSUE THREAD

**Issue by DragonStuff** [v3aqb/fwlite#41]
Hello,

Is it possible to proxy all requests so that none go direct? I am using fwlite to bypass a firewall and it seems to leak requests. Is there any rule I can set so that ALL requests go to my Shadowsocks server?

The "Global Agent" option does not work either :cry: 

Thanks!

**Comment by v3aqb** [comment]
To forward all requests to parent proxy, try edit userconf.ini:

    [fgfwproxy]
    profile = 4

In this case, loopback and LAN address still go direct.

**Comment by DragonStuff** [comment]
Thanks! Is there any way to set multiple Shadowsocks servers for one site?

For instance, my YouTube rule looks like this:
||youtube.com Arizona1

Is it possible to do:
||youtube.com Arizona1 Seattle1
So that the connections will be pooled between my two servers?

Thanks!

**Comment by v3aqb** [comment]
Nice idea.
You can set multiple parent proxy for one site now.

**Comment by DragonStuff** [comment]
Awesome! Good work. :+1: 

What files were edited as I am in the process of translating this into English and my latest download was yesterday?

Thanks!

**Comment by v3aqb** [comment]
Just fgfw-lite.py

**Comment by DragonStuff** [comment]
Last thing:
My password for the proxy server I need to pass through has an @ in it.

Is it possible to do the following? (example, not real credentials)
parentproxy = http://"0xdragon":"123456789@"@proxyserver

Also do you accept pull requests? Would be interested in helping you maintain this excellent work :+1: 

Thanks,
0xdragon.

**Comment by v3aqb** [comment]
From the RFC 1738:

"...Only alphanumerics [0-9a-zA-Z], the special characters "$-_.+!*'()," [not including the quotes - ed], and reserved characters used for their reserved purposes may be used unencoded within a URL."

You have to hex encode the @ in the URL:
    parentproxy = http://0xdragon:123456789%40@proxyserver

Now there is another problem:
parse.password = '123456789%40'

**Comment by DragonStuff** [comment]
So I'd have to write something to interpret hex encoded data in that string? 

Thanks!

**Comment by v3aqb** [comment]
I rewrited ParentProxy class to handle this problem, in 0.4 branch.

**Comment by DragonStuff** [comment]
Excellent! I'll attempt to implement the changes into my application.

Thanks.

**Comment by DragonStuff** [comment]
Hello,

Latest update appears to have broken the system:

Traceback (most recent call last):
  File "C:\Users\Alexander\Desktop\Linear0 - non update\Python27\python27.zip\SocketServer.py", line 595, in process_request_thread
  File "C:\Users\Alexander\Desktop\Linear0 - non update\Python27\python27.zip\SocketServer.py", line 334, in finish_request
  File "./fgfw-lite/fgfw-lite.py", line 292, in __init__
  File "C:\Users\Alexander\Desktop\Linear0 - non update\Python27\python27.zip\SocketServer.py", line 651, in __init__
  File "C:\Users\Alexander\Desktop\Linear0 - non update\Python27\python27.zip\BaseHTTPServer.py", line 340, in handle
  File "./fgfw-lite/fgfw-lite.py", line 407, in handle_one_request
  File "C:\Users\Alexander\Desktop\Linear0 - non update\Python27\python27.zip\BaseHTTPServer.py", line 328, in handle_one_request
  File "./fgfw-lite/fgfw-lite.py", line 743, in do_CONNECT
  File "./fgfw-lite/fgfw-lite.py", line 759, in _do_CONNECT
  File "./fgfw-lite/fgfw-lite.py", line 882, in _connect_via_proxy
  File "C:/Users/Alexander/Desktop/Linear0 - non update/fgfw-lite\connection.py", line 95, in create_connection
  File "C:/Users/Alexander/Desktop/Linear0 - non update/fgfw-lite\shadowsocks.py", line 29, in connect
  File "C:/Users/Alexander/Desktop/Linear0 - non update/fgfw-lite\connection.py", line 84, in create_connection
  File "C:/Users/Alexander/Desktop/Linear0 - non update/fgfw-lite\connection.py", line 31, in _create_connection
  File "C:/Users/Alexander/Desktop/Linear0 - non update/fgfw-lite\resolver.py", line 62, in resolver
AttributeError: 'NoneType' object has no attribute 'rr'
