### ISSUE TITLE
v5是不是不支持ipv6？

### ISSUE THREAD

**Issue by standritsu** [v3aqb/fwlite#67]
打开 http://www.firefox.net.cn/ 的话会有下面的错误，链接重置

07:41:34 fwlite_8118:ERROR TypeError('115.192.0.0 and 2400:8902::f03c:91ff:fe6e:1974 are not of the same version')
07:41:34 fwlite_8118:ERROR Traceback (most recent call last):
  File "D:\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 379, in _do_GET
    if self.getparent():
  File "D:\fwlite5\fwlite\fwlite_cli\proxy_handler.py", line 836, in getparent
    self._proxylist = self.conf.GET_PROXY.get_proxy(self.path, self.request_host, self.command, self.request_ip, self.server.profile)
  File "D:\fwlite5\fwlite\fwlite_cli\get_proxy.py", line 195, in get_proxy
    ifgfwed = self.ifgfwed(uri, host, port, ip, level)
  File "D:\fwlite5\fwlite\fwlite_cli\get_proxy.py", line 165, in ifgfwed
    if self.ip_in_china(host, ip):
  File "D:\fwlite5\Lib\repoze\lru\__init__.py", line 348, in cached_wrapper
    val = func(*args, **kwargs)
  File "D:\fwlite5\fwlite\fwlite_cli\get_proxy.py", line 121, in ip_in_china
    index = binary_search(self.china_ip_list, ip)
  File "D:\fwlite5\fwlite\fwlite_cli\get_proxy.py", line 114, in binary_search
    if arr[mid].network_address < hkey:
  File "D:\obj\Windows-Release\37amd64_Release\msi_python\zip_amd64\ipaddress.py", line 565, in __lt__
TypeError: 115.192.0.0 and 2400:8902::f03c:91ff:fe6e:1974 are not of the same version

**Comment by v3aqb** [comment]
thanks for reporting, new release uploaded
